# xp-forge/yaml

language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v5.2.0/setup' -O - | php
  - composer install --prefer-dist
  - echo "vendor/autoload.php" > composer.pth
  - echo "use=vendor/xp-framework/core" > xp.ini
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - ./unittest src/test/php

before_deploy:
  - export REL=`echo $TRAVIS_TAG | sed -e 's/^v//g'`
  - export MOD=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
  - wget https://github.com/xp-framework/build/releases/download/v3.0.0alpha2/travis.xar
  - ./xp -cp travis.xar net.xp_framework.build.Travis . $MOD $REL
  - cat glue.json

deploy:
  provider: releases
  file:
    - xp-$MOD-$REL.xar
    - xp-$MOD-test-$REL.xar
    - glue.json
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
    tags: true
    all_branches: true
    php: 5.4
  api_key:
    secure: "IGHVBdtAg//5ZAHXgCXMockEk193gtTebRKpWLiVSue0FH7/7n6Uw85fNYrI6RuXdXvvvAwjUzZyJ2ZgMNWwlo3ol3qdyE3sZCuy4kiiI843BxAPybGf4rz7AvdVYqLdMJW0S6FzF8ZzpS4lJSyL9TmznpbVn5gXrQJbRb983ok="
